### ISSUE TITLE
Crash  8.1.77 and 8.2.88 on Fabric 1.19.2

### ISSUE THREAD

**Issue by bawdeveloppement** [shedaniel/cloth-config#179]
[latest.log](https://github.com/shedaniel/cloth-config/files/9942953/latest.log)
[gradle.txt](https://github.com/shedaniel/cloth-config/files/9942959/gradle.txt)

As you can see there is a problem in the TitleScreenMixin.

Please tell me what you want more as information, it's my first ticket

**Comment by shedaniel** [comment]
Caused by modmenu
